import PAWSINU from "../assets/monsters/PAWSINU.png";
import REKAM from "../assets/monsters/REKAM.png";
import EVAA from "../assets/monsters/EVAA.png";
import IHSUS from "../assets/monsters/IHSUS.png";
import OANO from "../assets/monsters/OANO.png";
import ORENOM from "../assets/monsters/ORENOM.png";
import ANALOS from "../assets/monsters/ANALOS.png";
import HSACNIOCTIB from "../assets/monsters/HSACNIOCTIB.png";
import EHCANLAVA from "../assets/monsters/EHCANLAVA.png";
import ECNANIB from "../assets/monsters/ECNANIB.png";
import NIOCTIB from "../assets/monsters/NIOCTIB.png";
import MUEREHTE from "../assets/monsters/MUEREHTE.png";

// eslint-disable-next-line
export default [
  {
    name: "Pawsinu",
    image: PAWSINU,
    height: 50,
    width: 25,
    hp: 15,
    xp: 0,
    dmg: [0, 0],
    coins: [1, 5],
    loot: [
      { name: "Milkshake", r: 50 },
      { name: "Hotdog", r: 50 },
    ],
    rarity: 100,
    lvl: 0,
  },
  {
    name: "Rekam",
    image: REKAM,
    height: 50,
    width: 25,
    hp: 30,
    xp: 10,
    dmg: [0, 10],
    coins: [1, 2],
    loot: [
      { name: "Milkshake", r: 50 },
      { name: "Hamburger", r: 50 },
    ],
    rarity: 100,
    lvl: 0,
  },
  {
    name: "Evaa",
    image: EVAA,
    height: 50,
    width: 25,
    hp: 15,
    xp: 10,
    dmg: [0, 9],
    coins: [1, 5],
    loot: [
      { name: "Milkshake", r: 50 },
      { name: "Fries", r: 50 },
    ],
    rarity: 100,
    lvl: 0,
  },
  {
    name: "Ihsus",
    image: IHSUS,
    height: 50,
    width: 25,
    hp: 70,
    xp: 25,
    dmg: [0, 20],
    coins: [1, 10],
    loot: [
      { name: "Hotdog", r: 100 },
      { name: "Hand Axe", r: 80 },
      { name: "Wooden Shield", r: 70 },
    ],
    rarity: 100,
    lvl: 1,
  },
  {
    name: "Oano",
    image: OANO,
    height: 50,
    width: 25,
    hp: 50,
    xp: 20,
    dmg: [0, 10],
    coins: [1, 5],
    loot: [
      { name: "Hotdog", r: 100 },
      { name: "Hand Axe", r: 50 },
      { name: "Wooden Shield", r: 50 },
      { name: "Studded Club", r: 50 },
    ],
    rarity: 80,
    lvl: 2,
  },
  {
    name: "Orenom",
    image: ORENOM,
    height: 50,
    width: 25,
    hp: 55,
    xp: 25,
    dmg: [0, 14],
    coins: [1, 5],
    loot: [{ name: "Fries", r: 100 }],
    rarity: 70,
    lvl: 3,
  },
  {
    name: "Analos",
    image: ANALOS,
    height: 50,
    width: 25,
    hp: 260,
    xp: 150,
    dmg: [0, 105],
    coins: [1, 47],
    loot: [
      { name: "Hotdog", r: 50 },
      { name: "Short Sword", r: 30 },
      { name: "Battle Shield", r: 20 },
      { name: "Halberd", r: 20 },
      { name: "Plate Shield", r: 20 },
    ],
    rarity: 50,
    lvl: 10,
  },
  {
    name: "Hsac Nioctib",
    image: HSACNIOCTIB,
    height: 50,
    width: 25,
    hp: 240,
    xp: 150,
    dmg: [0, 129],
    coins: [0, 70],
    loot: [{ name: "Black Shield", r: 40 }],
    rarity: 50,
    lvl: 12,
  },
  {
    name: "Ehcanlava",
    image: EHCANLAVA,
    height: 50,
    width: 25,
    hp: 475,
    xp: 305,
    dmg: [0, 215],
    coins: [10, 60],
    loot: [
      { name: "Katana", r: 60 },
      { name: "Spike Sword", r: 40 },
      { name: "Vampire Shield", r: 10 },
    ],
    rarity: 30,
    lvl: 18,
  },
  {
    name: "Ecnanib",
    image: ECNANIB,
    height: 50,
    width: 25,
    hp: 1000,
    xp: 700,
    dmg: [0, 330],
    coins: [20, 60],
    loot: [
      { name: "Pizza", r: 80 },
      { name: "Long Sword", r: 50 },
      { name: "Broadsword", r: 40 },
      { name: "Serpent Sword", r: 30 },
      { name: "Dragon Hammer", r: 20 },
      { name: "Dragon Shield", r: 10 },
    ],
    rarity: 30,
    lvl: 20,
  },
  {
    name: "Nioctib",
    image: NIOCTIB,
    height: 50,
    width: 25,
    hp: 4000,
    xp: 2500,
    dmg: [150, 500],
    coins: [20, 150],
    loot: [
      { name: "Double Axe", r: 100 },
      { name: "Giant Sword", r: 20 },
      { name: "Golden Shield", r: 20 },
    ],
    rarity: 10,
    lvl: 35,
  },
  {
    name: "Muerehte",
    image: MUEREHTE,
    height: 50,
    width: 25,
    hp: 8200,
    xp: 6000,
    dmg: [300, 680],
    coins: [20, 250],
    loot: [
      { name: "Golden Sickle", r: 100 },
      { name: "Double Axe", r: 100 },
      { name: "Fire Axe", r: 80 },
      { name: "Demon Shield", r: 80 },
      { name: "Giant Sword", r: 80 },
      { name: "Mastermind Shield", r: 50 },
    ],
    rarity: 10,
    lvl: 50,
  },
];
